baseURL = ''
languageCode = 'en-us'
title = ''
theme = 'kaslaanka'

[params]
sitename = "Personal Blog"
copyrights = ""
defaultList = "global"
paginationLen = 3
projectsURL = "https://github.com/decidee/"

[[params.myprojects]]
name = "Project Habitual"
description = "Instant Message Automation"
url = "https://github.com/decidee/Project-Habitual"

[[params.myprojects]]
name = "Click"
description = "Internal Workflow Automation"
url = "https://github.com/decidee/Click"

[[menu.primary]]
name = "Home"
url = "/"
weight = 1

[[menu.primary]]
name = "Projects"
url = "/project"
weight = 2

[[menu.primary]]
name = "Blog"
url = "/blog"
weight = 3